---
- name: vCenter test
  hosts: localhost
  gather_facts: False
  vars_files:
    - off-list.yml
  tasks:
    - name: Poweroff virtual machine name {{ vm_name1 }}
      vmware_guest_powerstate:
        name: "{{ vm_name1 }}"
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: False
        folder: "{{ folder }}"
        state: powered-off
        
