---
- name: vCenter test
  hosts: localhost
  gather_facts: False
  vars_files:
    - off-list.yml
  tasks:
    - name: Poweroff virtual machine name {{ config.guestid== 'rhel7=64Guest' }}
      vmware_guest_powerstate:
        name: "{{ config.guestid== 'rhel7=64Guest' }}"
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: False
        folder: /Nativitas/hpe/
        state: powered-off
        
